- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
                - ansible-lint
                - yamllint
    gate:
      queue: core
      jobs:
        - linters
    kebechet-auto-gate:
      queue: core
      jobs:
        - linters
