- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
                - ansible-lint
                - yamllint
    gate:
      queue: thoth-station/core
      jobs:
        - linters
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: >
                https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/user-api/webhooks
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - linters
